### PR TITLE
Feature/fadi helm chart

### PR DESCRIPTION
**Pull request by alexnuttinck**
This pull request includes:

* ref to https://github.com/cetic/helm-fadi. A FADI Helm Chart that references all the others.
* fix for #7.
* a centralized values.yaml (under /helm folder) that contains same modifications we have done before.

Could you check my pull request @banzo ? Before merging into develop, and then into master.

### CODE REVIEW

**Comment by alexnuttinck** [comment]
Hmm.. Seems there is a bug with Minio:

```
Error creating: pods "fadi-minio-6ffb4d78f5-" is forbidden: error looking up service account fadi/fadi-minio: serviceaccount "fadi-minio" not found
```

**Comment by alexnuttinck** [comment]
Minio bug corrected in https://github.com/helm/charts/pull/15143

**Comment by alexnuttinck** [comment]
New release of the FADI helm Chart: https://github.com/cetic/helm-fadi/releases/tag/0.1.1
I think it can be merged now, @banzo

**Comment by banzo** [comment]
Note: I moved the sql script to create tables to the bd@ma repo on develop branch in the examples folder

**Pull request merged**
